from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest


SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(SRC))

from udp_protocol_portable import (  # noqa: E402
    build_robot_state_packet,
    parse_robot_command_packet,
)


# Golden packets generated by udp_protocol.cpython-311-x86_64-linux-gnu.so
# from rainbowroboticsofficial/rby1-sim-isaac:0.10.7-a_v1.2.
STATE_GOLDEN = bytes.fromhex(
    "24244e0002000000000000f43f0100000000000000f83f00000000000000c0"
    "000000000000d03f000000000000e0bf00000000000008400000000000001040"
    "00000000000014c000000000000018408d2525"
)
COMMAND_GOLDEN = bytes.fromhex(
    "24242f00020001000000000000f43f00000000000004c00300000004000000"
    "000000000000e03f000000000000e8bf01da2525"
)
COMMAND_WITH_PID_GOLDEN = bytes.fromhex(
    "24244f00020001000000000000f43f00000000000004c00300000004000000"
    "000000000000e03f000000000000e8bf0100000000000026400000000000002840"
    "00000000000035400000000000003640e82525"
)


def test_build_state_matches_vendor_codec() -> None:
    packet = build_robot_state_packet(
        1.25,
        np.array([True, False]),
        np.array([1.5, -2.0]),
        np.array([0.25, -0.5]),
        np.array([3.0, 4.0]),
        np.array([-5.0, 6.0]),
    )
    assert packet == STATE_GOLDEN


def test_parse_legacy_command_matches_vendor_codec() -> None:
    parsed = parse_robot_command_packet(COMMAND_GOLDEN)
    assert parsed is not None
    mode, target, feedback_gain, feedforward, finished, kp, kd = parsed
    np.testing.assert_array_equal(mode, [False, True])
    np.testing.assert_allclose(target, [1.25, -2.5])
    np.testing.assert_array_equal(feedback_gain, [3, 4])
    np.testing.assert_allclose(feedforward, [0.5, -0.75])
    assert finished is True
    assert kp is None
    assert kd is None


def test_parse_extended_pid_command_matches_vendor_codec() -> None:
    parsed = parse_robot_command_packet(COMMAND_WITH_PID_GOLDEN)
    assert parsed is not None
    *_, kp, kd = parsed
    np.testing.assert_allclose(kp, [11.0, 12.0])
    np.testing.assert_allclose(kd, [21.0, 22.0])


def test_rejects_bad_crc_and_inconsistent_state_lengths() -> None:
    corrupt = bytearray(COMMAND_GOLDEN)
    corrupt[10] ^= 0x01
    assert parse_robot_command_packet(bytes(corrupt)) is None

    with pytest.raises(ValueError, match="position has 1 entries; expected 2"):
        build_robot_state_packet(
            0.0,
            np.ones(2, dtype=bool),
            np.zeros(1),
            np.zeros(2),
            np.zeros(2),
            np.zeros(2),
        )
